apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "openQA.fullname" . }}
  labels:
{{ include "openQA.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openQA.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openQA.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: configmap
          configMap:
            name: {{ template "openQA.fullname" . }}-configmap
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9526
              protocol: TCP
           volumeMounts:
            - name: configmap
              mountPath: data/conf
          env:
            MODE: "webui"
            MOJO_LISTEN: "http://0.0.0.0:9526"
          livenessProbe:
            httpGet:
              path: /
              port: 9526
          readinessProbe:
            httpGet:
              path: /
              port: 9526
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
